language: python

git:
  depth: 3

branches:
  only:
    - master
    - /^(\d+\.)?(\d+\.)?\d+(-\w+)*$/

jobs:
  include:
    - stage: test
      name: "Python 3.5, Django 2.0, SQLite - Unit Test"
      python: 3.5
      env: EXAMPLE_ENGINE=sqlite3
      before_install: skip
      install: pip install django==2.0
      before_script: cd example && python manage.py migrate
      script: python manage.py test
    - name: "Python 3.6, Django 2.0, SQLite - Unit Test"
      python: 3.6
      env: EXAMPLE_ENGINE=sqlite3
      before_install: skip
      install: pip install django==2.0
      before_script: cd example && python manage.py migrate
      script: python manage.py test
    - name: "Python 3.5, Django 2.0, MySQL - Unit Test"
      python: 3.5
      services: mysql
      env:
        - EXAMPLE_ENGINE=mysql
        - EXAMPLE_NAME=example
        - EXAMPLE_USER=root
      before_install:
        - mysql -e 'CREATE DATABASE example CHARACTER SET utf8 COLLATE utf8_general_ci;'
      install:
        - pip install django==2.0
        - pip install mysqlclient
      before_script: cd example && python manage.py migrate
      script: python manage.py test
    - stage: deploy
      name: "Generate Doc & Upload to GitHub Pages"
      python: 3.6
      env: EXAMPLE_ENGINE=sqlite3
      before_install: skip
      install:
        - pip install django==2.0
        - pip install sphinx
      before_script: skip
      script: cd docs && make html
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: docs/_build/html
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: /^(\d+\.)?(\d+\.)?\d+(-\w+)*$/
